name = "flintlock-forms"
main = "src/index.js"
compatibility_date = "2024-12-01"

[vars]
RESEND_API_KEY = "YOUR_RESEND_API_KEY"
TO_EMAIL = "contact@flintlockagency.com"
FROM_EMAIL = "noreply@flintlockagency.com"
